-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 17:33:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `id_disciplina` INT(10) NOT NULL,
  `nome_disciplina` VARCHAR(45) NULL,
  `cpf_coordenador` VARCHAR(45) NULL,
  PRIMARY KEY (`id_disciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `id_turma` INT NOT NULL,
  `nome_turma` VARCHAR(45) NULL,
  `sala_turma` INT(5) NULL,
  PRIMARY KEY (`id_turma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `id_professor` INT NOT NULL,
  `nome_professor` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `sexo` VARCHAR(10) NULL,
  `salario` REAL NULL,
  `Disciplina_id_disciplina` INT(10) NOT NULL,
  `Turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`id_professor`, `Turma_id_turma`),
  INDEX `fk_Professor_Disciplina_idx` (`Disciplina_id_disciplina` ASC) VISIBLE,
  INDEX `fk_Professor_Turma1_idx` (`Turma_id_turma` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Disciplina`
    FOREIGN KEY (`Disciplina_id_disciplina`)
    REFERENCES `mydb`.`Disciplina` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Turma1`
    FOREIGN KEY (`Turma_id_turma`)
    REFERENCES `mydb`.`Turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
